### ISSUE TITLE
Attempt to creating a chat room

### ISSUE THREAD

**Issue by imdoingotherthings** [imdoingotherthings/bloc-chat-ember#1]
So my approach to enabling the user to create a new chat room was to loop through the data that we created in Firebase. That data which is our chatroom would be attached to the boostrap modal which when the user pressed "create room" the data would instantiate. 

What would be the best way to approach this feature in Ember? 

# Features that I need to add 

I have yet to attach code to the "create room" button which will create a new room and exit out of the bootstrap modal. 
![pop up window with a text field to name the room](https://cloud.githubusercontent.com/assets/20527548/21463116/8c2c0388-c919-11e6-9176-3478eb76d3eb.png)

**Comment by bdougie** [comment]
So I would start researching [here](https://github.com/firebase/emberfire/blob/master/docs/guide/saving-and-retrieving-data.md), it has clear examples and a good path for the next step. You will need to create a controller, `app/controllers/rooms.js`, use the CLI to do it. 

Every library, including Ember has documentation leverage them and try things out. 

Aside: You have a `bloc-chat` folder in the root of your project, most likely by mistake, try to take note of the quality of your project/code to be sure things like this don't slip by.

<img width="172" alt="screenshot 2016-12-23 15 33 01" src="https://cloud.githubusercontent.com/assets/5713670/21463877/2b2bf898-c925-11e6-9fb8-5b3c6fac4a69.png">

**Comment by imdoingotherthings** [comment]
Thanks for the documentation on EmberFire. So I've followed the instructions and created an action for the creation of a new room but could not see the data displaying on the page.

 I'll [commit](https://github.com/imdoingotherthings/bloc-chat-ember/tree/new-rooms) the changes now and show you what code I have added so far. 

I have a feeling that the naming is crucial and perhaps have miss used a name to reference.

**Comment by bdougie** [comment]
# Problem

There is a very clear error message here, did you look at that?

<img width="1124" alt="screenshot 2016-12-23 22 20 18" src="https://cloud.githubusercontent.com/assets/5713670/21465569/0fcfc168-c95e-11e6-9d0a-a3af9c06d175.png">

The first thing I would do in this situation is `console.log`

```js
export default Ember.Controller.extend({
  actions: {
    newChatRoom: function () {
     // when you hit the button the action never fires
      console.log("this never hits")

      var newRoom = this.store.createRecord('room', {
        name: this.get('name')
      });
      newRoom.save();
    }
  }
});
```

It is naming, the Room controller controls the Room template, but you are hitting the button in the application template.

What are your thoughts on this? Where should the action be placed?

Also did you note the differences in your input compared to the ember fire example:

```js
    // in the action, this.get("title") is referencing value's title
    {{input value=title placeholder="Title"}}
```

Check out some videos on the subject to get better acquainted with the Ember and Firebase relationship.  

https://www.emberscreencasts.com/posts/72-introduction-to-ember-actions
https://www.codeschool.com/screencasts/firebase-emberfire

Also read the docs:
https://guides.emberjs.com/v2.10.0/controllers/

finally here is a hint: Move the modal code to rooms.hbs, it shouldn't be on application.hbs

**Comment by imdoingotherthings** [comment]
__No link to from the modal to the controller__

So I've gone through the code a bit and watched the emberscreencast on actions. I understand what it's doing but can't seem to implement the same solution. It might be because I don't have a name to be referenced inside of the modal. 

At the moment my code for the action controller is this:

```
export default Ember.Controller.extend({
  actions: {
    newChatRoom: function () {
      console.log("room")
      var newRoom = this.store.createRecord('room', {
        name: "this room"
      });
      newRoom.save();
    }
  }
});
```

From my understanding, after the `createRecord` code, inside the curly brackets, we should have `title` which gives the instance a name. Following, we should have `this.set('<name>', true)` which sets the new instance. 

I could be wrong but this is what I understood after reading the documentation on Ember for `createRecord` and `actions`, also by watching the screencasts which are really well made. 

I am stuck on this at the moment. After this has all been done, I need to route the text field to the controller that way it saves the users text as the name of the new instance, in our case a new chat room.

**Comment by bdougie** [comment]
Is the branch you are working on GitHub? What do you have in your template? - only half the info is here. 

```js
// "this room" is off but in the right direction
   var newRoom = this.store.createRecord('room', {
        name: "this room"
      });
```

Based on this video https://www.emberscreencasts.com/posts/86-login-form

You should be able to call this.getProperties("room"). If you added a `{{ input value=room  }}` to the template you should then be able to pass the result to firebase in your `this.store.createRecord`

```js
export default Ember.Controller.extend({
  actions: {
    newChatRoom: function () {
      var room = this.getProperties("room")
      var newRoom = this.store.createRecord('room', {
        name: room
      });
      newRoom.save();
    }
  }
});
```

**Comment by imdoingotherthings** [comment]
So I completed the creation of a new chat room but, I can't seem to store the input from the text field. Instead, when we create a new room it generates `[object object]`. On another note, there's a duplicate `Room1` that I'm looking into. 

![object object](https://cloud.githubusercontent.com/assets/20527548/21756335/e93c33b4-d5d4-11e6-8b06-73be27c984e7.png)

My first guess after reading this [article](https://emberway.io/a-gentle-introduction-to-ember-2-0-8ef1f378ee4#.6fzv47rc4) was that there's no action being referenced in the `route.js` file. Continuing to read the article, I noticed that we don't have a `component.js` file which is going to send a value to the route. 

Other than that, the CSS is complete and the data is in sync with FireBase. 

[Latest commit](https://github.com/imdoingotherthings/bloc-chat-ember/tree/new-rooms)

*I know that I messed up on the naming for the commit as I was prompted with a conflict. So I committed the master file with `...` naming not knowing that I had previously merged `new-rooms`*

**Comment by bdougie** [comment]
Check your data in firebase, looks like you are saving your data differently than you are expecting to receive it.

 Also why are you list the rooms twice? https://github.com/imdoingotherthings/bloc-chat-ember/blob/cace4d78c9cd40c6534df301c9deaef23a910c1e/app/templates/rooms.hbs#L4-L5

A component is not needed for this and only adds a level complexity not need for this assignment.

**Comment by imdoingotherthings** [comment]
So I figured out that I was missing some key components to store the text from the text field. 
I'll link you the checkpoint and I also submitted it to Bloc although there is a minor issue. The new instance of the chat room duplicates itself and I'm not entirely sure as to why it is doing this.
As you could see here I created `Room 2` and is in sync with FireBase.

![room 2 created](https://cloud.githubusercontent.com/assets/20527548/21793689/637d8794-d6a8-11e6-880b-d4f6364cf443.png)

**FireBase**

![firebase](https://cloud.githubusercontent.com/assets/20527548/21793715/96cfd430-d6a8-11e6-906f-5c10dcee1ed5.png)

[Latest commit to master](https://github.com/imdoingotherthings/bloc-chat-ember)

I used the documentation from EmberFire here on GitHub to solve the issue. 
[EmberFire](https://github.com/firebase/emberfire/blob/master/docs/guide/saving-and-retrieving-data.md)
