### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by bdougie** [imdoingotherthings/bloc-chat-ember#4]
@imdoingotherthings try to open issues when there are some. It is much easier to assist this way than through slack messages.

I tried out ember-cookies and it has a complicated setup. I recommend using [ember-cookie-monster](https://www.npmjs.com/package/ember-cookie-monster) instead. You be able to create a new component for the cookie checking like so `ember g component cookie-store` and populate it with the boilerplate you see in the cookie monster description.

**Comment by bdougie** [comment]
@imdoingotherthings let me know if you were able to mirror the code from #5 and get the word `no` to render on the page.

Let me know so I can guide you on the next part which is setting the username in the cookie.

**Comment by imdoingotherthings** [comment]
@bdougie I just pushed this branch up to have something to work with. I did mirror your PR and if you'll see here, this is what I get on the page `localhost:4200/rooms`.

![text prompt](https://cloud.githubusercontent.com/assets/20527548/22136042/c20825a4-de86-11e6-91d8-7eaacbec16dc.png)

Although I have the cookies PR mirrored, I can't seem to get `no` to show up on the landing page. So I'll be working on this now.

**Comment by imdoingotherthings** [comment]
I see now reading over the ember-cookie-monster addon, that I have to create a function in order to display if we have cookies.

**Comment by bdougie** [comment]
It should be `cookie-store` not `cookie.store` https://github.com/imdoingotherthings/bloc-chat-ember/blob/username/app/templates/application.hbs#L11
 
There are errors in your code preventing me from spinning up the server. https://github.com/imdoingotherthings/bloc-chat-ember/pull/3/commits/790d8ca994b4e4a304eb394e8819e6a5e79dd8aa

**Comment by bdougie** [comment]
@asai I didn't see a response my comment above. Do you have time Saturday or Sunday evening to go through the next steps together? I would like to pair program to finish off this project
